# Generated by Django 5.0.1 on 2025-11-12 12:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("template_code", models.CharField(max_length=200)),
                ("name", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "email"), ("push", "push")],
                        default="email",
                        max_length=10,
                    ),
                ),
                ("language", models.CharField(default="en", max_length=10)),
                ("subject", models.CharField(blank=True, max_length=255, null=True)),
                ("body", models.TextField()),
                ("variables", models.JSONField(default=list)),
                ("version", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["template_code", "language", "version"],
                        name="templates_a_templat_378ec7_idx",
                    )
                ],
                "unique_together": {("template_code", "language", "version")},
            },
        ),
    ]
